### ISSUE TITLE
Outdated webpack version. Update to 2.2 from 1.14

### ISSUE THREAD

**Issue by mhornbacher** [learn-co-curriculum/react-passing-props-lab#10]
There is an issue with the `extract-text-webpack-plugin` on this lab causing weird issues:
`npm WARN extract-text-webpack-plugin@2.1.2 requires a peer of webpack@^2.2.0 but none was installed.`

Iv'e found on Ununtu 17.10 to fix this I need change the following line in `./package.json`
From:
`"webpack": "^1.14.0",`
To:
`"webpack": "^2.2.0",`

From what I can tell this does not cause additional issues.

**Comment by gj** [comment]
Fixed with #9.

Thanks @PCGeekBrain !

**Comment by mhornbacher** [comment]
No problem
